/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deskapp;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SHIVAANSH
 */
public class subcategory extends javax.swing.JFrame {

    /**
     * Creates new form subcategory
     */
    public subcategory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("manage subcategory");
        setLocation(new java.awt.Point(400, 250));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel1.setText("manage sub-category");

        jLabel2.setText("category");

        jLabel3.setText("sub-category name");

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "category id", "category name", "sub-category id", "sub-cat name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setResizable(false);
            table1.getColumnModel().getColumn(1).setResizable(false);
            table1.getColumnModel().getColumn(2).setResizable(false);
            table1.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("manage products?");

        jButton2.setText("add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("choose category?");

        jLabel6.setText("category id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(delete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2))
                                        .addGap(53, 53, 53)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(t2))))
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(update)
                            .addComponent(delete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4)
                    .addComponent(jButton5)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        categry c=new categry();
        c.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String path="jdbc:mysql://localhost/";
        String place="shivam";
        String user="root";
        String password="";
        t1.setEditable(false);
        t2.setEditable(false);
        update.setEnabled(false);
        delete.setEnabled(false);
        try {
            Connection conn=(Connection)DriverManager.getConnection(path+place,user,password);
            String qy="select * from subcat,category where subcat.catid=category.catid";
            try{
                PreparedStatement st=(PreparedStatement)conn.prepareStatement(qy);
                
                ResultSet rst=st.executeQuery();
                DefaultTableModel mymodel= (DefaultTableModel)table1.getModel();
                mymodel.setRowCount(0);
                if(rst.next()){
                    do{
                       String catid=rst.getString("catid"); 
                       String catname=rst.getString("catname");
                       String subid=rst.getString("subid");
                       String subname=rst.getString("subname");
                       
                       
                       Object rowdata[]={catid,catname,subid,subname};
                       mymodel.addRow(rowdata);
                    }
                    while(rst.next());
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"no more data");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,"unable to fetch data"+e);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"connection error"+ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:String path="jdbc:mysql://localhost/";
        String path="jdbc:mysql://localhost/";
        String place="shivam";
        String user="root";
        String password="";
        try {
            Connection conn=(Connection)DriverManager.getConnection(path+place,user,password);
            String qy="insert into subcat(catid,subname) values(?,?)";
            try{
                PreparedStatement st=(PreparedStatement)conn.prepareStatement(qy);
                st.setString(1,t2.getText());
                st.setString(2,t3.getText());
                int rowcount=st.executeUpdate();
                if(rowcount==1){
                    clear();
                    this.dispose();
                    subcategory sc=new subcategory();
                    sc.setVisible(true);
                    JOptionPane.showMessageDialog(rootPane,"sub-category added succesfully");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,"unable to add data"+e);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"connection error"+ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void table1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseReleased
        String path="jdbc:mysql://localhost/";
        String place="shivam";
        String user="root";
        String password="";
        update.setEnabled(true);
        delete.setEnabled(true);
        try {
            Connection conn=(Connection)DriverManager.getConnection(path+place,user,password);
            String qy="select * from subcat where subid=?";
            try{
                PreparedStatement st=(PreparedStatement)conn.prepareStatement(qy);
                st.setString(1,table1.getValueAt(table1.getSelectedRow(),2).toString());
                ResultSet rst=st.executeQuery();
                if(rst.next()){
                t1.setText(table1.getValueAt(table1.getSelectedRow(),1).toString());
                    t2.setText(rst.getString("catid"));
                    t3.setText(rst.getString("subname"));
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,"cant fetch data"+e);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"connectivity error"+e);
        }
    }//GEN-LAST:event_table1MouseReleased

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:String path="jdbc:mysql://localhost/";
        String path="jdbc:mysql://localhost/";
        String place="shivam";
        String user="root";
        String password="";
        try {
            Connection conn=(Connection)DriverManager.getConnection(path+place,user,password);
            String qy="update subcat set subname=? where subid=?";
            try{
                PreparedStatement st=(PreparedStatement)conn.prepareStatement(qy);
                st.setString(1,t3.getText());
                st.setString(2,table1.getValueAt(table1.getSelectedRow(),2).toString());
                int rowcount=st.executeUpdate();
                if(rowcount==1){
                    clear();
                    this.dispose();
                    subcategory sc=new subcategory();
                    sc.setVisible(true);
                    JOptionPane.showMessageDialog(rootPane,"sub-category updated succesfully");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,"cant fetch data"+e);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"connectivity error"+e);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:String path="jdbc:mysql://localhost/";
        String path="jdbc:mysql://localhost/";
        String place="shivam";
        String user="root";
        String password="";
        try {
            Connection conn=(Connection)DriverManager.getConnection(path+place,user,password);
            String qy="delete from subcat where subid=?";
            try{
                PreparedStatement st=(PreparedStatement)conn.prepareStatement(qy);
                st.setString(1,table1.getValueAt(table1.getSelectedRow(),2).toString());
                int rowcount=st.executeUpdate();
                if(rowcount==1){
                    clear();
                    this.dispose();
                    subcategory sc=new subcategory();
                    sc.setVisible(true);
                    JOptionPane.showMessageDialog(rootPane,"sub-category deleted succesfully");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,"cant fetch data"+e);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"connectivity error"+e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String empty=t3.getText();
        int l=empty.length();
        if(l!=0){
            categry c=new categry();
            products p=new products();
            subcategory sc=new subcategory();
            p.setVisible(true);
            this.dispose();
            String catid=t2.getText();
            p.t1.setText(catid);
            String subid=table1.getValueAt(table1.getSelectedRow(),2).toString();
            p.t2.setText(subid);
            String catname=table1.getValueAt(table1.getSelectedRow(),1).toString();
            p.catname.setText(catname);
            String subname=t3.getText();
            p.subname.setText(subname);
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"choose sub-category name from table");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
void clear(){
    t1.setText("");
    t2.setText("");
    t3.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subcategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField t1;
    public javax.swing.JTextField t2;
    public javax.swing.JTextField t3;
    private javax.swing.JTable table1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
